
2019-institutstag-molnar.html: 2019-institutstag-molnar.Rmd
	Rscript --vanilla -e 'rmarkdown::render("2019-institutstag-molnar.Rmd")'

pdf: 2019-institutstag-molnar.Rmd
	Rscript --vanilla -e 'rmarkdown::render("2019-institutstag-molnar.Rmd", output_format = "beamer_presentation")'
